### ISSUE TITLE
Additionally set `DuplicatesStrategy.EXCLUDE`?

### ISSUE THREAD

**Issue by sschuberth** [gradlex-org/reproducible-builds#2]
One thing [we do](https://github.com/oss-review-toolkit/ort/blob/c725523fee2d2d359da7694e8abab29118ab7c44/buildSrc/src/main/kotlin/ort-base-conventions.gradle.kts#L45-L49) on top of

https://github.com/gradlex-org/reproducible-builds/blob/9c84c8c0a5df089ff1c6b688855654b38dded193/src/main/java/org/gradlex/reproduciblebuilds/ReproducibleBuildsPlugin.java#L34-L39

is to set `duplicatesStrategy = DuplicatesStrategy.EXCLUDE`. Do you think this makes sense here, too?

**Comment by jjohannes** [comment]
Thank you for the thought. I would actually consider this an anti-pattern. 😄 

If you have duplicates, something is most likely wrong in the setup. **Duplicate** does **not** mean that you have two **completely identical** inputs, but two files with the same path, which could potentially have different content. This would silently drop one of these files.

**Comment by sschuberth** [comment]
Yes, I'm aware of what you're saying. But in strict terms of reproducible builds you could argue that you'd simply want to deterministically pick one of these files, not caring too much which one.

Anyway, in our case the addition of `DuplicatesStrategy.EXCLUDE` was just a work-around for https://youtrack.jetbrains.com/issue/IDEA-305759. Maybe it's just time to revert that work-around.

**Comment by jjohannes** [comment]
The standard behavior of Gradle here is to fail. Which is already reproducible. The build always fails with the same error.

The goal of the plugin is to provide better defaults where Gradle's standards are not deterministic.
