### ISSUE TITLE
Option to not set `preserveFileTimestamps`

### ISSUE THREAD

**Issue by boris-petrov** [gradlex-org/reproducible-builds#3]
Congrats on the new plugin!

In my `build.gradle` file I've added this comment:

```groovy
// should *not* add `preserveFileTimestamps = false` because Gradle
// puts the same last-modified timestamp for all files and Tomcat
// will send the same ETag even when a file is changed:
// https://mail-archives.apache.org/mod_mbox/tomcat-users/201909.mbox/%3C0be01580-54c6-5c4-16b7-000a577c4ebb%40profuzdigital.com%3E
```

In the [documentation](https://gradlex.org/reproducible-builds/#archive-tasks) I see that `preserveFileTimestamps` is set to `false`. Is it possible to somehow enable this plugin but make it *not* set that particular setting for reasons explained in the comment above?

**Comment by jjohannes** [comment]
Thank you for the feedback. The goal of the plugin is to give useful conventions that work for "most" cases, if you want your build to be reproducible. In my understanding, `preserveFileTimestamps = true` will lead to that no longer being the case. If you run the build at different points in time (without any caching), the Jar files will be different when you do a byte-by-byte comparison, as the class files inside(which all have the same content) have different timestamps.

My first thought would be that this plugin is then not useful for the case you talk about as you can't achieve this kind of reproducibility.

But still, everything the plugin does can be re-configured. So you can override any setting agin. In this case, you can do

```
tasks.withType<AbstractArchiveTask>().configureEach {
  preserveFileTimestamps = true
}
```

after you applied the plugin.

**Comment by boris-petrov** [comment]
I'm also confused by why that broke my code a while ago. I'll check it and see if I really have to put `preserveFileTimestamps = true`. Otherwise your example works fine so I'll close this issue, thanks!
